### ISSUE TITLE
Double clicking on command (CLI tool) does nothing on Windows

### ISSUE THREAD

**Issue by lightningquick** [ajitid/telltail-center#3]
The download ClI tool for windows does not run. Simply opens and closes in a flash. I did rename the tool to telltail.exe too. 
What sort of logs do you need.

**Comment by ajitid** [comment]
So the process in Windows would be:
1. Open the folder where you've downloaded Telltail CLI. It is probably Downloads folder, so open that using Explorer.
2. Check if you have Windows Terminal installed. If you do, type `wt` in location bar of Explorer and hit enter. Otherwise type `cmd` and hit enter. This will open a terminal in Downloads folder.
3. Now you can run the command like `.\telltail <whatever-your-command-is>`

**Comment by ajitid** [comment]
Hopefully that solves it. Closing for now.
